export function rewriteSitemapLocOrigins(xml: string, request: Request): string {
  const requestUrl = new URL(request.url);

  // Sitemap XML is generated by our backend, so rewriting plain <loc> values is
  // sufficient as long as that generator continues to emit raw absolute URLs.
  return xml.replace(/<loc>([^<]+)<\/loc>/g, (_match, rawUrl: string) => {
    try {
      const url = new URL(rawUrl);
      url.protocol = requestUrl.protocol;
      url.host = requestUrl.host;
      return `<loc>${url.toString()}</loc>`;
    } catch {
      return `<loc>${rawUrl}</loc>`;
    }
  });
}
